import { useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import type { BacktestResponse } from '../services/backtestApi'
import { BollingerBandsChart } from '../components/BollingerBandsChart'
import { EquityCurveChart } from '../components/EquityCurveChart'
import { MAChart } from '../components/MAChart'
import { RSIChart } from '../components/RSIChart'
import { MACDChart } from '../components/MACDChart'
import { buildRunLabel, loadLastRun, saveLastRun, saveRun, strategyLabel, type BacktestRun } from '../services/savedResultsStore'

function isValidDate(value: unknown): value is string {
  return typeof value === 'string' && !Number.isNaN(Date.parse(value))
}

function toFiniteNumber(value: unknown): number | null {
  if (typeof value === 'number') {
    return Number.isFinite(value) ? value : null
  }
  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value)
    return Number.isFinite(parsed) ? parsed : null
  }
  return null
}

export default function ResultsPage() {
  const location = useLocation()
  const routeState = location.state as { result?: BacktestResponse; run?: BacktestRun } | null
  const routeRun = routeState?.run
  const currentRun = routeState?.run ?? loadLastRun()
  const result = currentRun?.result ?? routeState?.result
  const [saveStatus, setSaveStatus] = useState('')

  useEffect(() => {
    if (routeRun) {
      saveLastRun(routeRun)
    }
  }, [routeRun])

  const metricDescriptions: Record<string, string> = {
    'Total Return': 'The overall profit/loss percentage generated by your trading strategy.',
    'Buy & Hold Return': 'What you would have made if you simply bought and held the stock the entire time.',
    'Max Drawdown': 'The largest peak-to-trough decline experienced during the backtest period.',
    'Sharpe Ratio': 'Risk-adjusted return metric. Higher values indicate better returns per unit of risk.',
    'Win Rate': 'Percentage of trades that were profitable (or closed with a gain).',
    'Profit Factor': 'Gross profit divided by gross loss. Higher ratios indicate better profitability.',
    'Number of Trades': 'Total number of buy and sell trades executed during the backtest.',
    'Final Value': 'The ending portfolio value after all trades and the backtest period.',
    'Volatility': 'Annualized standard deviation of daily returns (measures price fluctuations).',
    'Std Dev of Returns': 'Daily standard deviation of portfolio returns (measure of day-to-day volatility).',
  }

  const InfoIcon = ({ metric }: { metric: string }) => (
    <div className="tooltip-container">
      <div className="info-icon">i</div>
      <div className="tooltip-text">{metricDescriptions[metric]}</div>
    </div>
  )

  if (!result) {
    return (
      <main className="page">
        <h1>Results</h1>
        <p className="lead">No backtest results yet. Run a backtest first.</p>
      </main>
    )
  }

  const handleSaveRun = () => {
    if (!currentRun) {
      setSaveStatus('Run metadata is unavailable, so this result cannot be saved from the current page state.')
      return
    }

    const saved = saveRun(currentRun)
    setSaveStatus(`Saved ${saved.label} to this browser session.`)
  }

  const equityCurve = Array.isArray(result.equity_curve)
    ? result.equity_curve
        .map((point) => {
          const value = toFiniteNumber(point?.value)
          if (!isValidDate(point?.date) || value === null) {
            return null
          }
          return { date: point.date, value }
        })
        .filter((point): point is { date: string; value: number } => point !== null)
    : []

  const recentPoints = equityCurve.slice(-5)

  const isBollinger = result.strategy === 'bollinger_bands_strategy'
  const bollingerSeries = Array.isArray(result.bollinger_series)
    ? result.bollinger_series
        .map((point) => {
          const close = toFiniteNumber(point?.close)
          const upperBand = toFiniteNumber(point?.upper_band)
          const middleBand = toFiniteNumber(point?.middle_band)
          const lowerBand = toFiniteNumber(point?.lower_band)

          if (
            !isValidDate(point?.date) ||
            close === null ||
            upperBand === null ||
            middleBand === null ||
            lowerBand === null
          ) {
            return null
          }

          return {
            date: point.date,
            close,
            upper_band: upperBand,
            middle_band: middleBand,
            lower_band: lowerBand,
          }
        })
        .filter(
          (point): point is {
            date: string
            close: number
            upper_band: number
            middle_band: number
            lower_band: number
          } => point !== null,
        )
    : []

  return (
    <main className="page">
      <h1>Results</h1>
      <p className="lead">{currentRun ? buildRunLabel(currentRun) : 'Latest run summary'}</p>

      <section className="form-card" style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', alignItems: 'center' }}>
          <button type="button" onClick={handleSaveRun} disabled={!currentRun}>
            Save Result
          </button>
          <Link to="/saved-results" style={{ fontWeight: '600' }}>
            View Saved Results
          </Link>
        </div>
        {saveStatus ? <p style={{ marginBottom: 0, marginTop: '12px', color: 'rgb(75, 85, 99)' }}>{saveStatus}</p> : null}
      </section>

      {currentRun ? (
        <section className="form-card" style={{ marginBottom: '24px' }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '12px' }}>
            <div>
              <div style={{ fontSize: '12px', color: 'rgb(107, 114, 128)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Symbol</div>
              <div style={{ fontWeight: '700' }}>{currentRun.request.symbol.toUpperCase()}</div>
            </div>
            <div>
              <div style={{ fontSize: '12px', color: 'rgb(107, 114, 128)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Strategy</div>
              <div style={{ fontWeight: '700' }}>{strategyLabel(currentRun.request.strategy)}</div>
            </div>
            <div>
              <div style={{ fontSize: '12px', color: 'rgb(107, 114, 128)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Initial Capital</div>
              <div style={{ fontWeight: '700' }}>${currentRun.request.initialCapital.toLocaleString()}</div>
            </div>
            <div>
              <div style={{ fontSize: '12px', color: 'rgb(107, 114, 128)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Saved In Session</div>
              <div style={{ fontWeight: '700' }}>Yes</div>
            </div>
          </div>
        </section>
      ) : null}

      <section className="metrics-grid">
        <article className="metric-card">
          <div className="metric-header">
            <h2>Total Return</h2>
            <InfoIcon metric="Total Return" />
          </div>
          <p>{result.metrics.total_return_pct.toFixed(2)}%</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Buy & Hold Return</h2>
            <InfoIcon metric="Buy & Hold Return" />
          </div>
          <p>{result.metrics.buy_hold_return.toFixed(2)}%</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Max Drawdown</h2>
            <InfoIcon metric="Max Drawdown" />
          </div>
          <p>{(result.metrics.max_drawdown * 100).toFixed(2)}%</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Sharpe Ratio</h2>
            <InfoIcon metric="Sharpe Ratio" />
          </div>
          <p>{result.metrics.sharpe_ratio.toFixed(2)}</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Win Rate</h2>
            <InfoIcon metric="Win Rate" />
          </div>
          <p>{(result.metrics.win_rate * 100).toFixed(2)}%</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Profit Factor</h2>
            <InfoIcon metric="Profit Factor" />
          </div>
          <p>{result.metrics.profit_factor.toFixed(2)}</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Number of Trades</h2>
            <InfoIcon metric="Number of Trades" />
          </div>
          <p>{result.metrics.number_of_trades}</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Final Value</h2>
            <InfoIcon metric="Final Value" />
          </div>
          <p>${result.metrics.final_value.toLocaleString()}</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Volatility</h2>
            <InfoIcon metric="Volatility" />
          </div>
          <p>{result.metrics.volatility.toFixed(4)}</p>
        </article>
        <article className="metric-card">
          <div className="metric-header">
            <h2>Std Dev of Returns</h2>
            <InfoIcon metric="Std Dev of Returns" />
          </div>
          <p>{result.metrics.std.toFixed(4)}</p>
        </article>
      </section>

      <section className="equity-chart">
        <EquityCurveChart data={equityCurve} tradeSignals={result.trade_signals} />
      </section>

      {result.trade_signals && result.trade_signals.length > 0 ? (
        <section className="trade-signals-summary">
          <h2>Trading Signals</h2>
          <p style={{ marginBottom: '16px', fontSize: '14px', color: 'rgb(107, 114, 128)' }}>
            {result.trade_signals.length} signal(s) generated during the backtest period
          </p>
          <div style={{ 
            display: 'grid', 
            gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
            gap: '12px',
            maxHeight: '400px',
            overflowY: 'auto',
            padding: '12px',
            backgroundColor: 'rgb(249, 250, 251)',
            borderRadius: '8px',
            border: '1px solid rgb(229, 231, 235)'
          }}>
            {result.trade_signals.map((signal, index) => (
              <div key={index} style={{
                padding: '12px',
                backgroundColor: signal.signal === 1 ? 'rgba(34, 197, 94, 0.1)' : 'rgba(239, 68, 68, 0.1)',
                borderLeft: `4px solid ${signal.signal === 1 ? 'rgb(34, 197, 94)' : 'rgb(239, 68, 68)'}`,
                borderRadius: '6px',
                fontSize: '14px'
              }}>
                <div style={{ fontWeight: '600', color: signal.signal === 1 ? 'rgb(34, 197, 94)' : 'rgb(239, 68, 68)' }}>
                  {signal.signal === 1 ? '▲ BUY' : '▼ SELL'}
                </div>
                <div style={{ color: 'rgb(107, 114, 128)', marginTop: '4px' }}>
                  {signal.date}
                </div>
                <div style={{ color: 'rgb(75, 85, 99)', marginTop: '4px', fontSize: '13px' }}>
                  @ ${signal.price.toFixed(2)}
                </div>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      {isBollinger && bollingerSeries.length > 0 ? (
        <section className="equity-chart">
          <BollingerBandsChart data={bollingerSeries} />
        </section>
      ) : null}

      {result.strategy === 'ma_crossover' && result.ma_series && result.ma_series.length > 0 ? (
        <section className="equity-chart">
          <MAChart data={result.ma_series} />
        </section>
      ) : null}

      {result.strategy === 'rsi_strategy' && result.rsi_series && result.rsi_series.length > 0 ? (
        <section className="equity-chart">
          <RSIChart data={result.rsi_series} />
        </section>
      ) : null}

      {result.strategy === 'macd_strategy' && result.macd_series && result.macd_series.length > 0 ? (
        <section className="equity-chart">
          <MACDChart data={result.macd_series} />
        </section>
      ) : null}

      <section className="equity-preview">
        <h2>Recent Equity Points</h2>
        <div className="equity-points-container">
          {recentPoints.map((point, index) => {
            const percentChange = ((point.value - result.metrics.final_value) / result.metrics.final_value) * 100
            const isPositive = index === recentPoints.length - 1 || (index > 0 && recentPoints[index].value > recentPoints[index - 1].value)
            return (
              <div key={point.date} className="equity-point-card">
                <div className="point-date">{point.date}</div>
                <div className="point-value">${point.value.toLocaleString(undefined, { maximumFractionDigits: 2 })}</div>
                <div className={`point-change ${isPositive ? 'positive' : 'negative'}`}>
                  {isPositive ? '↗' : '↘'} {Math.abs(percentChange).toFixed(2)}%
                </div>
              </div>
            )
          })}
        </div>
      </section>
    </main>
  )
}
